config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /article/1/upvote
  def upvote
    @article = Article.find(params[:id])
    @article.score += 1
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article finally upvoted." }
        format.json { render :show, status: :updated, location: @article }
      else
        format.html { redirect_to :index }
        format.json { render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end


  def downvote
    @article = Article.find(params[:id])
    @article.score -= 1
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article finally downvoted." }
        format.json { render :show, status: :updated, location: @article }
      else
        format.html { redirect_to :index }
        format.json { render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.score = 0

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container m-auto p-6">
<p id="notice"><%= notice %></p>

<h1 class="heading text-2xl font-bold">Articles</h1>
<%= link_to 'New Article', new_article_path %>

   <div class="flex flex-col">
    <% @articles.each do |article| %>
      <div class="border p-6 rounded my-4">
        <h2><%= link_to article.title, article,:class => "text-blue-500 underline font-semibold" %></h2>
      </div>
    <% end %>
    </div>



</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="container m-auto p-6">
<p id="notice"><%= notice %></p>

<h1 class="text-2xl font-bold"><%= @article.title %></h1>

<p class="content py-4">
  <%= @article.body %>
</p>

<p>
  <strong>Score:</strong>
  <%= @article.score %>
</p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Upvote', upvote_article_path(@article), method: :post  %> |
<%= link_to 'Downvote', downvote_article_path(@article), method: :post %> |
<%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelfBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>